version: '3.8'
services:

  db:
    image: postgres:13
    restart: always
    network_mode: host
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    profiles:
      - prod
      - dev

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    network_mode: host
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - dev

  web-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: webProd
    network_mode: host
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - prod
volumes:
  db-data:

