import { getServerSession } from "next-auth";
import { AuthProvider } from "@/client/components/AuthProvider";
import { authOptions } from "@/server/auth";
import { type Session } from "next-auth/core/types";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session: Session = await getServerSession(authOptions);
  
  return (
    <html lang="en">
      <AuthProvider session={session}>
        <body>{children}</body>
      </AuthProvider>
    </html>
  )
}
