import { getServerSession } from "next-auth";
import { AuthProvider } from "@/client/components/AuthProvider";
import { authOptions } from "@/server/auth";
import { type Session } from "next-auth/core/types";
import '../../../styles/globals.css';
import { Header } from "@/client/components/Header";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session: Session = await getServerSession(authOptions);
  
  return (
    <body className="bg-background p-8 pb-3 h-[100dvh] flex flex-col justify-between items-start">
      <Header />
      <div className="overflow-y-auto min-h-[65vh] mb-5">
        {children}
      </div>
    </body>
  )
}
